import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAF4F0',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 16,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  iconButton: {
    padding: 4,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 110,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  sourceChip: {
    backgroundColor: '#FEE8D8',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  sourceChipText: {
    fontSize: 12,
    fontFamily: 'PlusJakartaSans_700Bold',
    color: '#D97B47',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  dateText: {
    fontSize: 13,
    fontFamily: 'PlusJakartaSans_500Medium',
    color: '#8A7D77',
  },
  headline: {
    fontSize: 26,
    fontFamily: 'PlusJakartaSans_800ExtraBold',
    color: '#2C2522',
    lineHeight: 34,
    marginBottom: 20,
  },
  articleImage: {
    width: '100%',
    height: 240,
    borderRadius: 20,
    marginBottom: 28,
  },
  swiperContainer: {
    alignItems: 'center',
  },
  flatlistContent: {
    alignItems: 'center',
  },
  contentCard: {
    width: width - 40,
    backgroundColor: '#FDF7F3',
    borderRadius: 20,
    padding: 24,
    minHeight: 200,
    justifyContent: 'flex-start',
    borderWidth: 1,
    borderColor: '#EBE1DA',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  cardNumberTag: {
    backgroundColor: '#FEE8D8',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    alignSelf: 'flex-start',
    marginBottom: 16,
  },
  cardNumberText: {
    fontSize: 12,
    fontFamily: 'PlusJakartaSans_700Bold',
    color: '#D97B47',
  },
  contentText: {
    fontSize: 17,
    fontFamily: 'PlusJakartaSans_500Medium',
    color: '#55433A',
    lineHeight: 28,
  },
  paginationContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 16,
  },
  dot: {
    width: 8,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#DBC1B6',
    marginHorizontal: 4,
  },
  activeDot: {
    width: 24,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#D97B47',
    marginHorizontal: 4,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 20,
    right: 20,
  },
  askButton: {
    backgroundColor: '#D97B47',
    borderRadius: 30,
    height: 58,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#D97B47',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 6,
  },
  askButtonText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontFamily: 'PlusJakartaSans_700Bold',
  },

  // ─── Modals ────────────────────────────────────────────────────────────────
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  chatContainer: {
    backgroundColor: '#FAF4F0',
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
    height: height * 0.88,
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 16,
  },
  chatHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  originalContainer: {
    backgroundColor: '#FAF4F0',
    borderRadius: 28,
    width: width * 0.9,
    maxHeight: height * 0.72,
    padding: 24,
    alignSelf: 'center',
    marginBottom: 80,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 20,
    elevation: 10,
  },
  originalTitle: {
    fontSize: 18,
    fontFamily: 'PlusJakartaSans_800ExtraBold',
    color: '#D97B47',
  },
  originalHeadlineText: {
    fontSize: 20,
    fontFamily: 'PlusJakartaSans_700Bold',
    color: '#2C2522',
    marginTop: 16,
    marginBottom: 12,
    lineHeight: 28,
  },
  originalContentText: {
    fontSize: 15,
    fontFamily: 'PlusJakartaSans_500Medium',
    color: '#55433A',
    lineHeight: 24,
  },
  readOriginalButton: {
    marginTop: 20,
    paddingVertical: 12,
    paddingHorizontal: 20,
    backgroundColor: '#D97B47',
    borderRadius: 14,
    alignItems: 'center',
  },
  readOriginalText: {
    fontSize: 15,
    fontFamily: 'PlusJakartaSans_700Bold',
    color: '#FFFFFF',
  },
  chatTitle: {
    fontSize: 26,
    fontFamily: 'PlusJakartaSans_800ExtraBold',
    color: '#2C2522',
  },
  chatSubtitle: {
    fontSize: 13,
    fontFamily: 'PlusJakartaSans_500Medium',
    color: '#8A7D77',
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 20,
  },
  chatHistoryContainer: {
    flex: 1,
  },

  // ─── Messages ──────────────────────────────────────────────────────────────
  botMessageRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    marginBottom: 14,
  },
  userMessageRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    marginBottom: 14,
  },
  botIconContainer: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#D97B47',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    shadowColor: '#D97B47',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  userIconContainer: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#EBE1DA',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },
  messageBubble: {
    maxWidth: '76%',
    padding: 14,
    borderRadius: 20,
  },
  botBubble: {
    backgroundColor: '#FFFFFF',
    borderBottomLeftRadius: 4,
    borderWidth: 1,
    borderColor: '#EBE1DA',
  },
  userBubble: {
    backgroundColor: '#D97B47',
    borderBottomRightRadius: 4,
  },
  messageText: {
    fontSize: 14,
    fontFamily: 'PlusJakartaSans_500Medium',
    color: '#2C2522',
    lineHeight: 22,
  },

  // ─── Suggestions ──────────────────────────────────────────────────────────
  suggestionsContainer: {
    marginTop: 16,
  },
  suggestionsTitle: {
    fontSize: 12,
    fontFamily: 'PlusJakartaSans_700Bold',
    color: '#8A7D77',
    marginBottom: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  suggestionChip: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 13,
    marginBottom: 8,
    borderWidth: 1.5,
    borderColor: '#FEE8D8',
  },
  suggestionText: {
    fontSize: 14,
    fontFamily: 'PlusJakartaSans_500Medium',
    color: '#D97B47',
    flex: 1,
  },

  // ─── Input ────────────────────────────────────────────────────────────────
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginTop: 14,
    borderWidth: 1.5,
    borderColor: '#EBE1DA',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  chatInput: {
    flex: 1,
    fontSize: 15,
    fontFamily: 'PlusJakartaSans_500Medium',
    color: '#2C2522',
    height: 40,
  },
  micButton: {
    padding: 8,
  },
  sendButton: {
    backgroundColor: '#D97B47',
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 6,
    shadowColor: '#D97B47',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 3,
  },
  sendButtonDisabled: {
    backgroundColor: '#DBC1B6',
    shadowOpacity: 0,
    elevation: 0,
  },
});
