import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F7EFE8', // Matching the warm beige background
    padding: 24,
    justifyContent: 'center',
  },
  backButton: {
    position: 'absolute',
    top: 60,
    left: 20,
    zIndex: 10,
    padding: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  header: {
    fontSize: 28,
    fontFamily: 'PlusJakartaSans_800ExtraBold',
    color: '#D97B47', // Layman title color matching front page
    marginBottom: 8,
    textAlign: 'center',
  },
  headerBlack: {
    fontSize: 22,
    fontFamily: 'PlusJakartaSans_700Bold',
    color: '#2C2522',
    marginBottom: 8,
    textAlign: 'center',
  },
  subHeader: {
    fontSize: 13,
    color: '#655A55',
    fontFamily: 'PlusJakartaSans_500Medium',
    marginBottom: 24,
    textAlign: 'center',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 3,
    marginBottom: 32,
  },
  inputWrapper: {
    marginBottom: 20,
  },
  labelContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  label: {
    fontSize: 11,
    color: '#655A55',
    fontFamily: 'PlusJakartaSans_700Bold',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  forgotText: {
    fontSize: 12,
    color: '#D97B47',
    fontFamily: 'PlusJakartaSans_700Bold',
  },
  inputField: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F7EFE8',
    borderRadius: 12,
    paddingHorizontal: 16,
    height: 52,
  },
  inputIcon: {
    marginRight: 12,
  },
  input: {
    flex: 1,
    fontSize: 15,
    color: '#2C2522',
    fontFamily: 'PlusJakartaSans_500Medium',
  },
  eyeIcon: {
    marginLeft: 12,
  },
  errorText: {
    color: '#ba1a1a',
    fontFamily: 'PlusJakartaSans_500Medium',
    fontSize: 13,
    marginBottom: 16,
    textAlign: 'center',
  },
  buttonPrimary: {
    backgroundColor: '#D97B47',
    height: 56,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    marginBottom: 24,
    shadowColor: '#D97B47',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  buttonPrimaryText: {
    color: '#ffffff',
    fontSize: 16,
    fontFamily: 'PlusJakartaSans_700Bold',
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#EBE1DA',
  },
  dividerText: {
    marginHorizontal: 16,
    color: '#8A7D77',
    fontSize: 11,
    fontFamily: 'PlusJakartaSans_700Bold',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  socialButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 16,
  },
  socialButton: {
    flex: 1,
    backgroundColor: '#FDF7F3',
    borderWidth: 1,
    borderColor: '#EBE1DA',
    height: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  socialButtonText: {
    color: '#2C2522',
    fontSize: 14,
    fontFamily: 'PlusJakartaSans_700Bold',
  },
  footerContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: 20,
  },
  footerText: {
    color: '#655A55',
    fontSize: 14,
    fontFamily: 'PlusJakartaSans_500Medium',
  },
  footerLink: {
    color: '#D97B47',
    fontSize: 14,
    fontFamily: 'PlusJakartaSans_700Bold',
    marginLeft: 4,
  },
});
